package view;

import javax.swing.JOptionPane;

public class FRMenu extends javax.swing.JFrame {
    private String email;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    
    /**
     * Creates new form FRMenu
     */
    public FRMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MICadUsuario = new javax.swing.JMenuItem();
        MICadFornecedor = new javax.swing.JMenuItem();
        MICadProduto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MIConUsuario = new javax.swing.JMenuItem();
        MIConFornec = new javax.swing.JMenuItem();
        MIConProdutos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MIOrdemCompras = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MIOrdemVendas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MIHistMov = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MISobre = new javax.swing.JMenuItem();
        MISair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ferramentas.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 450));

        jMenu1.setMnemonic('C');
        jMenu1.setText("Cadastro");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MICadUsuario.setMnemonic('U');
        MICadUsuario.setText("Usuario");
        MICadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(MICadUsuario);

        MICadFornecedor.setMnemonic('F');
        MICadFornecedor.setText("Fornecedor");
        MICadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(MICadFornecedor);

        MICadProduto.setMnemonic('P');
        MICadProduto.setText("Produto");
        MICadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(MICadProduto);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('o');
        jMenu2.setText("Consulta");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MIConUsuario.setMnemonic('U');
        MIConUsuario.setText("Usuários");
        MIConUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(MIConUsuario);

        MIConFornec.setText("Fornecedores");
        MIConFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConFornecActionPerformed(evt);
            }
        });
        jMenu2.add(MIConFornec);

        MIConProdutos.setMnemonic('P');
        MIConProdutos.setText("Produtos");
        MIConProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(MIConProdutos);

        jMenuBar1.add(jMenu2);

        jMenu4.setMnemonic('m');
        jMenu4.setText("Compras");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MIOrdemCompras.setMnemonic('O');
        MIOrdemCompras.setText("Ordem Compras");
        MIOrdemCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIOrdemComprasActionPerformed(evt);
            }
        });
        jMenu4.add(MIOrdemCompras);

        jMenuBar1.add(jMenu4);

        jMenu5.setMnemonic('V');
        jMenu5.setText("Vendas");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MIOrdemVendas.setMnemonic('O');
        MIOrdemVendas.setText("Ordem Vendas");
        MIOrdemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIOrdemVendasActionPerformed(evt);
            }
        });
        jMenu5.add(MIOrdemVendas);

        jMenuBar1.add(jMenu5);

        jMenu6.setMnemonic('E');
        jMenu6.setText("Estoque");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MIHistMov.setText("Histórico de movimentações");
        MIHistMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIHistMovActionPerformed(evt);
            }
        });
        jMenu6.add(MIHistMov);

        jMenuBar1.add(jMenu6);

        jMenu3.setMnemonic('A');
        jMenu3.setText("Ajuda");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MISobre.setMnemonic('S');
        MISobre.setText("Sobre");
        MISobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MISobreActionPerformed(evt);
            }
        });
        jMenu3.add(MISobre);

        jMenuBar1.add(jMenu3);

        MISair.setMnemonic('S');
        MISair.setText("Sair");
        MISair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MISair.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                MISairMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        MISair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MISairMouseClicked(evt);
            }
        });
        jMenuBar1.add(MISair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MICadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadProdutoActionPerformed
        new FRCadProduto(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MICadProdutoActionPerformed

    private void MICadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadUsuarioActionPerformed
        new FRCadUsuario(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MICadUsuarioActionPerformed

    private void MIConUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConUsuarioActionPerformed
        new FRConUsuario(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MIConUsuarioActionPerformed

    private void MISobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MISobreActionPerformed
        new FRSobre(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MISobreActionPerformed

    private void MICadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadFornecedorActionPerformed
        new FRCadFornecedor(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MICadFornecedorActionPerformed

    private void MIConFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConFornecActionPerformed
        new FRConFornecedor(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MIConFornecActionPerformed

    private void MIConProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConProdutosActionPerformed
        new FRConProduto(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MIConProdutosActionPerformed

    private void MISairMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_MISairMenuKeyPressed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja encerrar a aplicação?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if(resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_MISairMenuKeyPressed

    private void MIOrdemComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIOrdemComprasActionPerformed
        new FROrdemCompra(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MIOrdemComprasActionPerformed

    private void MISairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MISairMouseClicked
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja encerrar a aplicação?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if(resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_MISairMouseClicked

    private void MIOrdemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIOrdemVendasActionPerformed
        FROrdemVenda ordVnd = new FROrdemVenda(this, rootPaneCheckingEnabled);
        ordVnd.setEmail(this.getEmail());
        ordVnd.setVisible(true);
    }//GEN-LAST:event_MIOrdemVendasActionPerformed

    private void MIHistMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIHistMovActionPerformed
        new FRGerEstoque(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MIHistMovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MICadFornecedor;
    private javax.swing.JMenuItem MICadProduto;
    private javax.swing.JMenuItem MICadUsuario;
    private javax.swing.JMenuItem MIConFornec;
    private javax.swing.JMenuItem MIConProdutos;
    private javax.swing.JMenuItem MIConUsuario;
    private javax.swing.JMenuItem MIHistMov;
    private javax.swing.JMenuItem MIOrdemCompras;
    private javax.swing.JMenuItem MIOrdemVendas;
    private javax.swing.JMenu MISair;
    private javax.swing.JMenuItem MISobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
