/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UsuarioController;
import javax.swing.JOptionPane;
import javax.swing.ViewportLayout;

/**
 *
 * @author S.Lucas
 */
public class FRMenu extends javax.swing.JFrame {

    /**
     * Creates new form FRMenu
     */
    public FRMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MICadUsuario = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MIProduto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MIConUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MIConProdutos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MIOrdemCompras = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MIOrdemVendas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MISobre = new javax.swing.JMenuItem();
        MISair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 132, 116));

        jMenu1.setMnemonic('C');
        jMenu1.setText("Cadastro");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MICadUsuario.setMnemonic('U');
        MICadUsuario.setText("Usuario");
        MICadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(MICadUsuario);

        jMenuItem2.setMnemonic('F');
        jMenuItem2.setText("Fornecedor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        MIProduto.setMnemonic('P');
        MIProduto.setText("Produto");
        MIProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(MIProduto);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('o');
        jMenu2.setText("Consulta");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MIConUsuario.setMnemonic('U');
        MIConUsuario.setText("Usuários");
        MIConUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(MIConUsuario);

        jMenuItem1.setText("Fornecedores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        MIConProdutos.setMnemonic('P');
        MIConProdutos.setText("Produtos");
        jMenu2.add(MIConProdutos);

        jMenuBar1.add(jMenu2);

        jMenu4.setMnemonic('m');
        jMenu4.setText("Compras");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MIOrdemCompras.setMnemonic('O');
        MIOrdemCompras.setText("Ordem Compras");
        jMenu4.add(MIOrdemCompras);

        jMenuBar1.add(jMenu4);

        jMenu5.setMnemonic('V');
        jMenu5.setText("Vendas");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MIOrdemVendas.setMnemonic('O');
        MIOrdemVendas.setText("Ordem Vendas");
        jMenu5.add(MIOrdemVendas);

        jMenuBar1.add(jMenu5);

        jMenu3.setMnemonic('A');
        jMenu3.setText("Ajuda");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MISobre.setMnemonic('S');
        MISobre.setText("Sobre");
        MISobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MISobreActionPerformed(evt);
            }
        });
        jMenu3.add(MISobre);

        jMenuBar1.add(jMenu3);

        MISair.setMnemonic('S');
        MISair.setText("Sair");
        MISair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MISair.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MISairMenuSelected(evt);
            }
        });
        MISair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MISairMouseClicked(evt);
            }
        });
        jMenuBar1.add(MISair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MIProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIProdutoActionPerformed
        new FRCadProduto(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MIProdutoActionPerformed

    private void MICadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadUsuarioActionPerformed
        new FRCadUsuario(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MICadUsuarioActionPerformed

    private void MIConUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConUsuarioActionPerformed
        new FRConUsuario(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MIConUsuarioActionPerformed

    private void MISobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MISobreActionPerformed
        new FRSobre(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_MISobreActionPerformed

    private void MISairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MISairMouseClicked
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja encerrar a aplicação?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if(resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_MISairMouseClicked

    private void MISairMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MISairMenuSelected
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja encerrar a aplicação?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if(resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_MISairMenuSelected

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new FRCadFornecedor(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FRConFornecedor(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MICadUsuario;
    private javax.swing.JMenuItem MIConProdutos;
    private javax.swing.JMenuItem MIConUsuario;
    private javax.swing.JMenuItem MIOrdemCompras;
    private javax.swing.JMenuItem MIOrdemVendas;
    private javax.swing.JMenuItem MIProduto;
    private javax.swing.JMenu MISair;
    private javax.swing.JMenuItem MISobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
